/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursval;

import java.util.*;
import javax.swing.table.TableModel;

/**
 *
 * @author Alexander
 */
public class MainForm extends java.awt.Frame {

    
     public Map<String, String> valutesMap = null;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        String url1 = Cursval.urlValutes1;
        String xmlContent = HttpReq.sendGetRequest(url1);
        try{
            valutesMap = Cursval.parseValutes(xmlContent);
            for (String code: valutesMap.keySet()){
                jComboBox1.addItem(valutesMap.get(code).trim());
            }
        }catch(Exception e){
            System.out.println(e.toString());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("Валюта");
        jPanel1.add(jLabel1);

        jPanel1.add(jComboBox1);

        jLabel2.setText("с ");
        jPanel1.add(jLabel2);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(120, 20));
        jFormattedTextField1.setValue(new Date(new Date().getTime() - 10000));
        jPanel1.add(jFormattedTextField1);

        jLabel3.setText(" по ");
        jPanel1.add(jLabel3);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField2.setPreferredSize(new java.awt.Dimension(120, 20));
        jFormattedTextField2.setValue(new Date());
        jPanel1.add(jFormattedTextField2);

        jButton1.setText("Получить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 200));

        jList1.setPreferredSize(new java.awt.Dimension(450, 4000));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String code = "R01235";
        
                for ( String key: this.valutesMap.keySet() ){
                    System.out.println("map: "+valutesMap.get(key));
                    System.out.println("combo: "+jComboBox1.getSelectedItem().toString());
                    if ( this.valutesMap.get(key).equals(jComboBox1.getSelectedItem().toString()) ){
                        code = key;
                        System.out.println("key="+key);
                    }
                        
                }
        String url = Cursval.url + "date_req1="+jFormattedTextField1.getText();
        url += "&date_req2="+jFormattedTextField2.getText()+"&VAL_NM_RQ="+ code;        
        String content = HttpReq.sendGetRequest(url);
        try{
            List<Cursval.Curs> curses =  Cursval.parseCurses(content);
            Cursval.printCurses(curses);
            int row = 0;
   
            String[] listData = new String[curses.size()+1]; 
            listData[0] = jComboBox1.getSelectedItem().toString();
            for (Cursval.Curs curs: curses){
               
                listData[row+1] = curs.getDate() + "   " + curs.getCurs()/curs.getNominal()  + "     " + curs.getValuta();
                row++;
            }
            jList1.setListData(listData);
           
            
        }catch(Exception e){
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
